add_executable(ch01_hello hello.cpp)
add_executable(ex01_01 ex01_01.cpp)
add_executable(ex01_02 ex01_02.cpp)
add_executable(ex01_03 ex01_03.cpp)
add_executable(ex01_04 ex01_04.cpp)
add_executable(ex01_05 ex01_05.cpp)
add_executable(ex01_07 ex01_07.cpp)
add_executable(ex01_08 ex01_08.cpp)
add_executable(ex01_09 ex01_09.cpp)
add_executable(ex01_10 ex01_10.cpp)
add_executable(ex01_11 ex01_11.cpp)
add_executable(ex01_12 ex01_12.cpp)
add_executable(ex01_13 ex01_13.cpp)
add_executable(ex01_15 ex01_15.cpp)
add_executable(ex01_16 ex01_16.cpp)
add_executable(ex01_18 ex01_18.cpp)
add_executable(ex01_20 ex01_20.cpp)
add_executable(ex01_21 ex01_21.cpp)
add_executable(ex01_22 ex01_22.cpp)
add_executable(ex01_23 ex01_23.cpp)