file(GLOB experiment_sources "*.cpp")

foreach(source_file ${experiment_sources})
    get_filename_component(executable_name ${source_file} NAME_WE)
    if(NOT executable_name STREQUAL "var_declaration_vs_definition" AND NOT executable_name STREQUAL "external_definition")
        add_executable(${executable_name} ${source_file})
        target_include_directories(${executable_name} PRIVATE ${CMAKE_SOURCE_DIR}/include)
        target_link_libraries(${executable_name} PRIVATE pch)
    endif()
endforeach()

add_subdirectory(compound_types)
add_subdirectory(conversions)
add_subdirectory(variables)
add_subdirectory(representation)
add_subdirectory(literals)
add_subdirectory(const)
add_subdirectory(type_aliases)
add_subdirectory(type_deduction)
add_subdirectory(loops)
add_subdirectory(vector)
